# databricks files location config
FILES_LOCATION_CONF:
  workspace:
    scripts: "scripts" #default
  dbfs:
    scripts: "scripts" #default
    job_configs: "job_configs"
    specification_mappings: "specification_mappings"



