name: call-workflow-build-release-package

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  call-devops-workflow:
    name: Call DevOps Workflow
    uses: mdf-sandbox/sample-devops/.github/workflows/reusable-workflow-build-release-package.yml@main
    with:
      repository: ${{ github.repository }}
      head_ref: ${{ github.head_ref }}
    secrets: inherit
    permissions:
      contents: write