name: call-workflow-build-prerelease-package

on:
  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Bumping pre-release version from branch (main or release/**)
        default: main
      bump_version_mode:
        type: choice
        description: Bumping pre-release version to
        options:
         - premajor
         - preminor

jobs:
  call-devops-workflow:
    name: Call DevOps Workflow
    uses: mdf-sandbox/sample-devops/.github/workflows/reusable-workflow-build-prerelease-package.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ inputs.branch }}
      bump_version_mode: ${{ inputs.bump_version_mode }}
    secrets: inherit
    permissions:
      contents: write