name: call-workflow-build-patch-package

on:
  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  call-devops-workflow:
    name: Call DevOps Workflow
    uses: mdf-sandbox/sample-devops/.github/workflows/reusable-workflow-build-patch-package.yml@main
    with:
      repository: ${{ github.repository }}
    secrets: inherit
    permissions:
      contents: write