name: call-workflow-prebuild

on:
  pull_request:
   types: [ opened, reopened ]
   branches: [ main ]

  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  call-devops-workflow:
    name: Call DevOps Workflow
    uses: mdf-sandbox/sample-devops/.github/workflows/reusable-workflow-prebuild.yml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref }}
    secrets: inherit
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write