name: devops-build-patch-package-workflow-caller

on:
  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  call-devops-workflow:
    name: Call DevOps Workflow
    uses: mdf-sandbox/sample-devops/.github/workflows/devops-build-patch-package-workflow.yml@main
    with:
      repository: ${{ github.repository }}
    secrets: inherit
    permissions:
      contents: write